### ISSUE TITLE
Build fails with Terminal 0.3.0

### ISSUE THREAD

**Issue by franziskuskiefer** [AeneasVerif/eurydice#10]
The build fails with

```
File "bin/main.ml", line 41, characters 23-36:
41 |   let terminal_width = Terminal.Size.(match get_dimensions () with Some d -> d.columns | None -> 80) in
```

when using the current version of `Terminal` (0.3.0). Downgrading to 0.2.2 solves the issue.

**Comment by msprotz** [comment]
The error message is: `Error: Unbound module Terminal.Size`

**Comment by msprotz** [comment]
https://github.com/craigfe/progress/issues/42

**Comment by msprotz** [comment]
Temporarily worked around in 94eb31d, let's see what upstream says. Thanks for the bug report.

**Comment by msprotz** [comment]
I don't know how to set up the build so that `dune` refuses to proceed unless the correct terminal version is installed. @W95Psp? but at least if you `opam upgrade terminal`, then you should be good
