### ISSUE TITLE
Enums are not translated correctly

### ISSUE THREAD

**Issue by franziskuskiefer** [AeneasVerif/eurydice#102]
The following Rust code

```rust
enum Error1 {
    Reason1 = 1,
    Reason2 = 2,
}

enum Error2 {
    Reason1 = 3,
    Reason2 = 4,
}
```

Is translated into

```c
#define eurydice_tests_Reason1 0
#define eurydice_tests_Reason2 1

typedef uint8_t eurydice_tests_Error1;

typedef eurydice_tests_Error1 eurydice_tests_Error2;
```

**Comment by msprotz** [comment]
Right so this is the conflation of two issues.

1. Enum definitions are hash-consed (which is fine), since it optimizes code quality
2. We ignore the value of an enum tag

Fixing the latter will fix this issue. I don't think 1. is a problem
