### ISSUE TITLE
Fix Compound literals for MSVC C++

### ISSUE THREAD

**Issue by franziskuskiefer** [AeneasVerif/eurydice#24]
The MSVC C++ compiler does not support compound literals. So we need to update the code generation to properly generate code that can be used from C++.

In `eurydice_glue.h` we add something like this.

```c
#if defined(__cplusplus)
    #define CLITERAL(type)      type
#else
    #define CLITERAL(type)      (type)
#endif
```

Then every such invocation needs to change to
```c
CLITERAL(type){...}
```

In `eurydice_glue.h` manually, but in the generated code we need this pattern as well.

I'm not sure if the fix is here or in karamel.

**Comment by msprotz** [comment]
https://github.com/AeneasVerif/eurydice/commit/81373480992bc1088818884d8572bf2711d25d63
